version: "3"

services:
  web:
    build: .
    container_name: aspire_web
    command: sh startup.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app/code
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_PASSWORD=${1}
      - DJANGO_EMAIL=${2}
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: aspireAPIDB
      POSTGRES_USER: aspireAdmin
      POSTGRES_PASSWORD: aspirePass2023
    ports:
      - "5432:5432"