# Generated by Django 4.2 on 2023-04-30 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("term", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("PAID", "PAID"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loan Application",
                "verbose_name_plural": "Loan Applications",
            },
        ),
        migrations.CreateModel(
            name="LoanRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date_of_payment", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("PAID", "PAID")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Repayment",
                "verbose_name_plural": "Loan Repayments",
            },
        ),
    ]
